opensrp/opensrp-plan-evaluator

.gitignore
pom.xml
src/main/java/org/smartregister/pathevaluator/PlanEvaluator.java
src/test/java/org/smartregister/pathevaluator/PlanEvaluatorTest.java

Add ability to evaluate fhir path expressions

---

.travis.yml
README.md
pom.xml

Add travis and coveralls

---

pom.xml
src/main/java/org/smartregister/pathevaluator/TriggerEvent.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/utils/PlanHelper.java
src/test/java/org/smartregister/pathevaluator/PlanEvaluatorTest.java

Project structure

---

src/main/java/org/smartregister/domain/PlanDefinition.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/utils/PlanHelper.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java

Use Opensrp plan domain classes

---

pom.xml
src/main/java/org/smartregister/pathevaluator/PathEvaluatorLibrary.java
src/main/java/org/smartregister/pathevaluator/action/ActionHelper.java
src/main/java/org/smartregister/pathevaluator/condition/ConditionHelper.java
src/main/java/org/smartregister/pathevaluator/dao/BaseProvider.java
src/main/java/org/smartregister/pathevaluator/dao/ClientDao.java
src/main/java/org/smartregister/pathevaluator/dao/ClientProvider.java
src/main/java/org/smartregister/pathevaluator/dao/LocationDao.java
src/main/java/org/smartregister/pathevaluator/dao/LocationProvider.java
src/main/java/org/smartregister/pathevaluator/dao/TaskDao.java
src/main/java/org/smartregister/pathevaluator/dao/TaskProvider.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/test/java/org/smartregister/pathevaluator/PathEvaluatorLibraryTest.java
src/test/java/org/smartregister/pathevaluator/TestData.java
src/test/java/org/smartregister/pathevaluator/action/ActionHelperTest.java
src/test/java/org/smartregister/pathevaluator/condition/ConditionHelperTest.java
src/test/java/org/smartregister/pathevaluator/dao/ClientProviderTest.java
src/test/java/org/smartregister/pathevaluator/dao/LocationProviderTest.java
src/test/java/org/smartregister/pathevaluator/dao/TaskProviderTest.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java

Simplify Data access interfaces

---

src/main/java/org/smartregister/domain/Action.java
src/main/java/org/smartregister/domain/DynamicValue.java
src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/test/java/org/smartregister/pathevaluator/TestData.java
src/test/java/org/smartregister/pathevaluator/task/TaskHelperTest.java

https://github.com/OpenSRP/opensrp-plan-evaluator/issues/34

WIP : Add Action dynamicValue

---

pom.xml
src/main/java/org/smartregister/converters/ClientConverter.java
src/main/java/org/smartregister/domain/Expression.java
src/main/java/org/smartregister/pathevaluator/PathEvaluatorLibrary.java
src/main/java/org/smartregister/pathevaluator/ResourceType.java
src/main/java/org/smartregister/pathevaluator/TriggerType.java
src/main/java/org/smartregister/pathevaluator/action/ActionHelper.java
src/main/java/org/smartregister/pathevaluator/condition/ConditionHelper.java
src/main/java/org/smartregister/pathevaluator/dao/ClientProvider.java
src/main/java/org/smartregister/pathevaluator/dao/LocationProvider.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/main/java/org/smartregister/pathevaluator/trigger/TriggerHelper.java
src/test/java/org/smartregister/pathevaluator/PathEvaluatorLibraryTest.java
src/test/java/org/smartregister/pathevaluator/action/ActionHelperTest.java
src/test/java/org/smartregister/pathevaluator/condition/ConditionHelperTest.java
src/test/java/org/smartregister/pathevaluator/dao/ClientProviderTest.java
src/test/java/org/smartregister/pathevaluator/dao/LocationProviderTest.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java

Event submission triggering, Conditions references and description, bug fixes

---

pom.xml
src/main/java/org/smartregister/domain/Client.java

Add TeamId and LocationId to client domain

---

pom.xml
src/main/java/org/smartregister/converters/EventConverter.java
src/main/java/org/smartregister/converters/LocationConverter.java
src/main/java/org/smartregister/domain/BaseDataObject.java
src/main/java/org/smartregister/domain/Event.java
src/main/java/org/smartregister/domain/Expression.java
src/main/java/org/smartregister/domain/Obs.java
src/main/java/org/smartregister/domain/Task.java
src/main/java/org/smartregister/pathevaluator/PathEvaluatorLibrary.java
src/main/java/org/smartregister/pathevaluator/action/ActionHelper.java
src/main/java/org/smartregister/pathevaluator/condition/ConditionHelper.java
src/main/java/org/smartregister/pathevaluator/dao/ClientProvider.java
src/main/java/org/smartregister/pathevaluator/dao/LocationProvider.java
src/main/java/org/smartregister/pathevaluator/dao/TaskDao.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/main/java/org/smartregister/pathevaluator/trigger/TriggerHelper.java
src/test/java/org/smartregister/pathevaluator/PathEvaluatorLibraryTest.java
src/test/java/org/smartregister/pathevaluator/TestData.java
src/test/java/org/smartregister/pathevaluator/action/ActionHelperTest.java
src/test/java/org/smartregister/pathevaluator/condition/ConditionHelperTest.java
src/test/java/org/smartregister/pathevaluator/dao/ClientProviderTest.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java
src/test/java/org/smartregister/pathevaluator/task/TaskHelperTest.java
src/test/java/org/smartregister/pathevaluator/trigger/TriggerHelperTest.java

Event submission triggering

---

pom.xml

Use maven deploy plugin only to avoid duplicate deploy tasks

---

pom.xml
src/main/java/org/smartregister/pathevaluator/dao/TaskDao.java
src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/test/java/org/smartregister/pathevaluator/task/TaskHelperTest.java

https://github.com/OpenSRP/opensrp-plan-evaluator/issues/43

Add an Interface to TaskDAO for checking if a task if already generated 

---

src/main/java/org/smartregister/domain/Obs.java

Added @JsonIgnore annotation to ignore method while serialization or deserialization.
Added this annotation to fix unit tests on the server core side.

Added jsonIgnore annotation to fix unit tests on the core side

---

pom.xml
src/main/java/org/smartregister/domain/Task.java
src/main/java/org/smartregister/pathevaluator/dao/TaskDao.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/test/java/org/smartregister/pathevaluator/TestData.java
src/test/java/org/smartregister/pathevaluator/task/TaskHelperTest.java

https://github.com/OpenSRP/opensrp-plan-evaluator/issues/57

57 : Add functionality to Populate a Task from action Dynamic variables

---

src/main/java/org/smartregister/pathevaluator/PathEvaluatorLibrary.java
src/test/java/org/smartregister/pathevaluator/PathEvaluatorLibraryTest.java

Support string evaluation

---

src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/test/java/org/smartregister/pathevaluator/TestData.java
src/test/java/org/smartregister/pathevaluator/task/TaskHelperTest.java

Add support for Dynamic expressions in action dynamic Values

---

pom.xml
src/main/java/org/smartregister/domain/PhysicalLocation.java
src/main/java/org/smartregister/domain/PlanDefinition.java

Implement with Serializable on PlanDefinition and PhysicalLocation.

350 implement acl

---

pom.xml
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/plan/PlanHelper.java

Correct Trigger evaluation and null location dao

---

pom.xml
src/main/java/org/smartregister/pathevaluator/dao/QueuingHelper.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java

https://github.com/OpenSRP/opensrp-server-core/issues/286

WIP :  Implement Queuing for Server side plan evaluation 

---

src/main/java/org/smartregister/pathevaluator/dao/QueuingHelper.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java

https://github.com/OpenSRP/opensrp-server-core/issues/286
Extension of MVP - breaking it down further into entities

286 : Add method in QueuingHelper class

---

pom.xml
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java

Process child jurisdictions in parallel 

---

pom.xml
src/main/java/org/smartregister/domain/Action.java
src/main/java/org/smartregister/domain/Condition.java
src/main/java/org/smartregister/domain/DynamicValue.java
src/main/java/org/smartregister/domain/Goal.java
src/main/java/org/smartregister/domain/Jurisdiction.java
src/main/java/org/smartregister/domain/Period.java
src/main/java/org/smartregister/domain/PlanDefinition.java
src/main/java/org/smartregister/domain/Target.java
src/main/java/org/smartregister/domain/Trigger.java

https://github.com/OpenSRP/opensrp-server-web/issues/479

479 : Implement classes with serializable

---

src/main/java/org/smartregister/pathevaluator/PathEvaluatorLibrary.java
src/main/java/org/smartregister/pathevaluator/action/ActionHelper.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/test/java/org/smartregister/pathevaluator/PathEvaluatorLibraryTest.java
src/test/java/org/smartregister/pathevaluator/action/ActionHelperTest.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java
src/test/java/org/smartregister/pathevaluator/task/TaskHelperTest.java
src/test/resources/Questionnaire.json

Support tasks for location from person events, bug fixes

---

pom.xml
src/main/java/org/smartregister/pathevaluator/action/ActionHelper.java
src/main/java/org/smartregister/pathevaluator/dao/StockDao.java
src/test/java/org/smartregister/pathevaluator/action/ActionHelperTest.java

https://github.com/OpenSRP/opensrp-plan-evaluator/issues/83
Fix

Fix in inventory task generation

---

pom.xml
src/main/java/org/smartregister/domain/Inventory.java
src/main/java/org/smartregister/domain/Stock.java

https://github.com/OpenSRP/opensrp-server-core/issues/392

392 : add providerId in Inventory Object

---

pom.xml
src/main/java/org/smartregister/domain/Inventory.java

https://github.com/OpenSRP/opensrp-server-core/issues/399

399 : Add accountability end date in Inventory domain

---

pom.xml
src/main/java/org/smartregister/pathevaluator/action/ActionHelper.java
src/test/java/org/smartregister/pathevaluator/action/ActionHelperTest.java

Allow fetch of global tasks for a questionnaire

---

pom.xml
src/main/java/org/smartregister/converters/EventConverter.java
src/main/java/org/smartregister/pathevaluator/action/ActionHelper.java
src/main/java/org/smartregister/pathevaluator/dao/EventDao.java
src/main/java/org/smartregister/pathevaluator/plan/PlanEvaluator.java
src/main/java/org/smartregister/pathevaluator/task/TaskHelper.java
src/test/java/org/smartregister/pathevaluator/action/ActionHelperTest.java
src/test/java/org/smartregister/pathevaluator/plan/PlanEvaluatorTest.java

Support questionnaire response as action subject

---

pom.xml
src/main/java/org/smartregister/domain/Stock.java

https://github.com/OpenSRP/opensrp-server-web/issues/711

711 : Add product catalogue to stock object

---

pom.xml
src/main/java/org/smartregister/domain/Inventory.java

https://github.com/OpenSRP/opensrp-server-core/issues/411

411 : Fix Quantity bug on add inventory

---

pom.xml
src/main/java/org/smartregister/converters/StockConverter.java
src/test/java/org/smartregister/converters/StockConverterTest.java

Resolves https://github.com/OpenSRP/opensrp-plan-evaluator/issues/118

118 : Fix a cause of an exception occured while evaluating the Product Check action

---

pom.xml
src/main/java/org/smartregister/domain/Practitioner.java
src/test/java/org/smartregister/domain/PractitionerTest.java

See https://github.com/opensrp/opensrp-server-core/issues/521 for details

Add server version, date edited, date created attributes to Practitioner entity
